= Test Framework - Binnacle

Proposal for a Test framework with the focus for Tester's delight!

Automating tests in a distributed setup is always hard. Binnacle aims
to simplify the ergonomics so that a tester without Programming
language expertise can adapt to this quickly.

If someone knows which command to test, then write that command with
the prefix `TEST`. For example, the command `touch
/var/www/html/index.html` tries to create a file inside the directory
to see if it succeeds. To convert this into a test case, write as
below.

[source,ruby]
----
# File: hello.t
TEST "touch /var/www/html/index.html"
---

That's it! Run the test file using the binnacle command, and it gives
the beautiful Output as below.

[source,console]
----
$ binnacle hello.t
TOTAL: 1  PASSED: 1  FAILED: 0  SKIPPED: 0  TODOs: 0
Result: PASS
DURATION: 0.124071 seconds
----

The verbose(`-v`) Output gives other useful details about executed
command and error lines in case of errors.

Learning the new programming language is not required to write test
cases.

**Note**: This framework is not for Unit testing

== Install

Download the latest release with the command

----
curl -L https://github.com/kadalu/binnacle/releases/download/0.1.0/binnacle -o binnacle
----

Make the `binnacle` file executable.

----
chmod +x ./binnacle
----

Move the binary in to your PATH.

----
sudo mv ./binnacle /usr/local/bin/binnacle
----

Test to ensure the version you installed is up-to-date

----
$ binnacle --version
----

== Usage

----
binnacle -v <testfile>
----

For example,

[source,console]
----
$ binnacle -v sample.t
----

== Features

TODO
