= Introduction

Binnacle is inspired by the Testing framework used in the https://gluster.org[GlusterFS] project. GlusterFS uses http://testanything.org[TAP(Test Anything protocol)] based test framework. All the tests are written in bash script.

Automating tests in a distributed setup is always hard. Binnacle aims to simplify the ergonomics so that a tester without Programming language expertise can adapt to this quickly.

[source,ruby]
----
# file: test_ssh_key_initialized.t
TEST "stat ~/.ssh/id_rsa.pub"
----

and run the test using,

[source,console]
----
$ binnacle test_ssh_key_initialized.t
TOTAL: 1  PASSED: 1  FAILED: 0  SKIPPED: 0  TODOs: 0
Result: PASS
DURATION: 0.118192311 seconds
----

Use `-v` for verbose output. Verbose output is compatible with TAP.

[source,console]
----
$ binnacle test_ssh_key_initialized.t -v
1..1
ok       1 - node=local cmd="stat ~/.ssh/id_rsa.pub"
TOTAL: 1  PASSED: 1  FAILED: 0  SKIPPED: 0  TODOs: 0
Result: PASS
DURATION: 0.115948522 seconds
----

Similar to `TEST` keyword, Binnacle supports many keywords. Read more about supported keywords link:keywords.adoc[here].

== Multi node support

Easily run all the tests from your laptop that runs tests via `ssh` or `docker exec`. Below example shows that hostname is properly set on all the machines.

[source,ruby]
----
USE_NODE "node1.example.com"
EXPECT "node1.example.com", "hostname"

USE_NODE "node2.example.com"
EXPECT "node2.example.com", "hostname"

USE_NODE "node3.example.com"
EXPECT "node3.example.com", "hostname"
----

Default remote plugin is `ssh`. To use docker plugin,

[source,ruby]
----
USE_REMOTE_PLUGIN "docker"

USE_NODE "node1.example.com"
EXPECT "node1.example.com", "hostname"

USE_NODE "node2.example.com"
EXPECT "node2.example.com", "hostname"

USE_NODE "node3.example.com"
EXPECT "node3.example.com", "hostname"
----

What if we need to set default node to execute all the commands but only a few commands to be executed in another node.

[source,ruby]
----
# Default node setup
USE_NODE "node1.example.com"

TEST "stat /var/www/html/index.html"
EXPECT "node1.example.com", "hostname"

USE_NODE "node2.example.com" do
  EXPECT "node2.example.com", "hostname"
end
----

== Remote plugins

When node is selected as non local, then Binnacle uses remote plugin. Default plugin is `ssh`.

`ssh` and `docker` are the supported plugins.

For example,

[source,ruby]
----
USE_REMOTE_PLUGIN "ssh"
USE_NODE "node1.example.com"
TEST "command1 arg1 arg2"
----

Above command will be executed as below when ssh plugin is used.

[source,bash]
----
ssh node1.example.com 'command1 arg1 arg2'
----

[source,ruby]
----
USE_REMOTE_PLUGIN "docker"
USE_NODE "node1.example.com"
TEST "command1 arg1 arg2"
----

Above command will be executed as below when docker plugin is used.

[source,bash]
----
docker exec -i node1.example.com /bin/bash -c 'command1 arg1 arg2'
----
