= Quick Start

Binnacle is a simple Test framework with the focus on Tester's delight.

Download and install using the following commands. Ruby should be installed on the machine where it needs to work.

[source,console]
----
$ curl -fsSL https://github.com/kadalu/binnacle/releases/latest/download/install.sh | sudo bash -x
----

Test to ensure the version you installed is up-to-date

[source,console]
----
$ binnacle --version
----

Lets write a quick test file that tests a file exists or not

[source,ruby]
----
# file: hello.t
TEST "stat /var/www/html/index.html"
----

Now run this test file by running,

[source,console]
----
$ binnacle hello.t -v
Indexing test files... done.  tests=1  test_files=1  duration_seconds=0


------- STARTED(tests=1, file="/hello.t")
not ok   1 - node=local cmd="TEST stat /var/www/html/index.html"
# stat: cannot stat '/var/www/html/index.html': No such file or directory
------- COMPLETED(NOT OK, tests=1, passed=0, failed=1)


STATUS  TESTS  PASSED  FAILED  DUR(SEC)  SPEED(TPM)  INDEX DUR(SEC)  FILE
=========================================================================
NOT OK      1       0      1          0           0               0  /hello.t
-------------------------------------------------------------------------
NOT OK      1       0      1          0           0               0

Result: Fail
----

If that file exists then it will print the output as below

[source,console]
----
$ binnacle hello.t -v
Indexing test files... done.  tests=1  test_files=1  duration_seconds=0


------- STARTED(tests=1, file="/hello.t")
ok       1 - node=local cmd="TEST stat /var/www/html/index.html"
------- COMPLETED(OK, tests=1, passed=1, failed=0)


STATUS  TESTS  PASSED  FAILED  DUR(SEC)  SPEED(TPM)  INDEX DUR(SEC)  FILE
=========================================================================
OK          1       1      0          0           0               0  /hello.t
-------------------------------------------------------------------------
OK          1       1      0          0           0               0

Result: Pass
----

Use `-v` two times to show the output of each commands.
