= Syntax

Test starts with an Binnacle keyword `TEST`, `EXPECT`, `TRUE` etc. The command should be written in quotes. For example,

[source,ruby]
----
TEST "stat ~/.ssh/id_rsa.pub"
----

If a test expects a different return code other than `0`, then

[source,ruby]
----
TEST 1, "ls /non/existing/dir"
----

== Comments

Use `#` for writing comments.

[source,ruby]
----
# This is comment
TEST "echo Hello"
----

== Arguments

Arguments to Binnacle keywords are separated using `,`(comma).

[source,ruby]
----
TEST 1, "ls /non/existing/dir"
----

== Using Variables

Binnacle supports Ruby style variables, for example

[source,ruby]
----
kubectl = "microk8s.kubectl"

TEST "#{kubectl} get pods"
----

== Capturing the output of a command

Easily capture the output of a command and use that value for validating the output. For example,

[source,ruby]
----
hostname = TEST "hostname"
TRUE hostname == "node1.example.com", "node1.example.com hostname test", "Actual: #{hostname}"
----

== Block Syntax

Some keywords allows to limit the execution only within a block. Block starts with `do` and ends with `end` keyword. For example, the tests within the Block are executed in `node1.example.com`

[source,ruby]
----
# Executes in Local node
TEST "echo Hello"

NODE "node1.example.com" do
  TEST "echo Hello"
end

# Again in local node
TEST "echo Hello"
----

== Running tests in loop

Binnacle supports using list of values and run the tests in loop. Please note, It will lead to undefined behaviour if the list of items is dependent on previous tests.

[source,ruby]
----
nodes = ["node1.example.com", "node2.example.com", "node3.example.com"]

nodes.each do |node|
  # Set node
  NODE node

  # Validate the hostname set properly
  EXPECT node, "hostname"
end
----

Loop syntax is same as in Ruby.
