name: Release

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - "*"

env:
  binnacle_version: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

jobs:
  publish-artifacts:
    name: Publish binnacle file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate Single file
      run: |
          BINNACLE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make build
    - name: Upload binnacle to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin/binnacle
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
