name: Release

on:
  push:
    # Publish `1.2.3` tags as releases.
    tags:
      - "*"

env:
  binnacle_version: $(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

jobs:
  publish-artifacts:
    name: Publish kadalu-binnacle
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate the Version
      run: |
        BINNACLE_VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,') make gen-version
    - name: Publish gem
      uses: dawidd6/action-publish-gem@v1
      with:
        # Optional, will publish to RubyGems if specified
        api_key: ${{secrets.RUBYGEMS_API_KEY}}
        # Optional, will publish to GitHub Packages if specified
        github_token: ${{secrets.GITHUB_TOKEN}}
